graph TB
    subgraph External Systems
        direction TB
        UserInterfaces("User Interfaces<br/>(Web UI, Slack, CLI)")
        APIs("External Systems & APIs")
    end

    subgraph SolaceAgentMesh ["Solace Agent Mesh"]
        direction TB
        subgraph Gateways
            WebUIGateway("Web UI Gateway")
            CustomGateway("Custom Gateway")
        end

        Broker("Solace Event Broker<br/>(A2A Protocol Over Topics)")

        subgraph AgentHosts ["Agent Hosts (SAC Applications)"]
            AgentHost1("Agent Host<br/>(Runs Agent A)")
            AgentHost2("Agent Host<br/>(Runs Agent B)")
            AgentHostN("...")
        end
    end

    subgraph BackendServices [Backend Services & Tools]
        direction TB
        LLM("Large Language Models")
        CustomTools("Custom Tools<br/>(Python, MCP)")
        DataStores("Databases & Vector Stores")
        ArtifactService("Artifact Service<br/>(Filesystem, Cloud Storage)")
    end

    %% Connections
    UserInterfaces -- Interacts with --> Gateways
    APIs -- Interacts with --> Gateways

    Gateways -- Pub/Sub --> Broker
    AgentHosts -- Pub/Sub --> Broker

    AgentHost1 -- Uses --> LLM
    AgentHost1 -- Uses --> CustomTools
    AgentHost1 -- Uses --> DataStores
    AgentHost1 -- Uses --> ArtifactService

    AgentHost2 -- Uses --> LLM
    AgentHost2 -- Uses --> CustomTools
    AgentHost2 -- Uses --> DataStores
    AgentHost2 -- Uses --> ArtifactService


    %% Styling
    classDef externalBoxes fill:#FFF7C2,stroke:#03213B,stroke-width:2px,color:#03213B;
    classDef gatewayContainer fill:#F4F4F4,stroke:#03213B,stroke-width:2px,color:#03213B;
    classDef gatewayBoxes fill:#C2F7FF,stroke:#03213B,stroke-width:2px,color:#03213B;
    classDef mesh fill:#E8FFF0,stroke:#03213B,stroke-width:2px,color:#03213B;
    classDef broker fill:#00C895,stroke:#03213B,stroke-width:2px,color:#03213B;
    classDef agentContainer fill:#F4F4F4,stroke:#03213B,stroke-width:2px,color:#03213B;
    classDef agentBoxes fill:#C2F7FF,stroke:#03213B,stroke-width:2px,color:#03213B;
    classDef serviceBoxes fill:#FFF7C2,stroke:#03213B,stroke-width:2px,color:#03213B

    class UserInterfaces,APIs externalBoxes;
    class WebUIGateway,CustomGateway gatewayBoxes;
    class Gateways gatewayContainer;
    class Broker broker;
    class SolaceAgentMesh mesh;
    class AgentHosts agentContainer;
    class AgentHost1,AgentHost2,AgentHostN agentBoxes;
    class LLM,CustomTools,DataStores,ArtifactService serviceBoxes;