import google.adk.sessions.database_session_service
"""ADK session DB upgrade

Revision ID: e2902798564d
Revises: 
Create Date: 2025-11-12 10:59:41.286752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2902798564d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('custom_metadata', google.adk.sessions.database_session_service.DynamicJSON(), nullable=True))
    op.add_column('events', sa.Column('usage_metadata', google.adk.sessions.database_session_service.DynamicJSON(), nullable=True))
    op.add_column('events', sa.Column('citation_metadata', google.adk.sessions.database_session_service.DynamicJSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'citation_metadata')
    op.drop_column('events', 'usage_metadata')
    op.drop_column('events', 'custom_metadata')
    # ### end Alembic commands ###
