"""add_project_id_to_sessions_and_foreign_key

Revision ID: eb39112e89f7
Revises: c61144add8c5
Create Date: 2025-09-17 17:58:26.260247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb39112e89f7'
down_revision: Union[str, Sequence[str], None] = 'c61144add8c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('project_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'sessions', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'project_id')
    # ### end Alembic commands ###