"""Add template id to projects

Revision ID: 860225db9872
Revises: fab5a36baf17
Create Date: 2025-08-22 16:33:23.228617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '860225db9872'
down_revision: Union[str, Sequence[str], None] = 'fab5a36baf17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_global', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('template_id', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('created_by_user_id', sa.String(), nullable=False))
    op.alter_column('projects', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'projects', 'projects', ['template_id'], ['id'])
    op.create_foreign_key(None, 'sessions', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.alter_column('projects', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('projects', 'created_by_user_id')
    op.drop_column('projects', 'template_id')
    op.drop_column('projects', 'is_global')
    # ### end Alembic commands ###