name: Check External Contributor

on:
  pull_request:
    types: [opened, reopened]

jobs:
  check-external-contributor:
    uses: SolaceDev/solace-public-workflows/.github/workflows/check-external-contributor.yml@feat/check-external-contributor
    with:
      github_team_slug: solace-ai
      label_name: external contributor
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
