name: Check External Contributor

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main
      - feat/external-contributor

jobs:
  check-external-contributor:
    name: Check External Contributor
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: Check External Contributor
        uses: SolaceDev/solace-public-workflows/check-external-contributor@feat/check-external-contributor
        with:
          github_team_slug: solace-ai
          label_name: external contributor
          github-token: ${{ secrets.GITHUB_TOKEN }}
