name: Test hatch_release_security_checks (branch test)

on:
  push:

permissions:
  contents: read
  checks: write
  pull-requests: read
  packages: read

jobs:
  security-checks:
    uses: SolaceDev/solace-public-workflows/.github/workflows/hatch_release_security_checks.yml@feat/dynamic-github-org-image-pull
    with:
      fossa_check: true
    secrets:
      FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
