name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        required: true
        description: "Version bump type for PyPI package & Git tag"
        options:
          - patch
          - minor
          - major

permissions:
  id-token: write
  checks: write
  contents: write
  packages: write

jobs:
  release:
    uses: SolaceDev/solace-public-workflows/.github/workflows/hatch_release_pypi.yml@test-prisma
    with:
      ENVIRONMENT: pypi
      version: ${{ github.event.inputs.version }}
      whitesource_project_name: "solace-agent-mesh"
      whitesource_product_name: "solaceai"
      prisma_check: true
      sonarqube_hotspot_check: true
      npm_package_path: client/webui/frontend
      node_version: 20
      npm_lock_file: package-lock.json
      pypi-project: solace-agent-mesh

    secrets:
      COMMIT_KEY: ${{ secrets.COMMIT_KEY }}

  build_and_push_docker:
    name: Build and Push Docker Image
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Push Docker Image using Composite Action
        uses: ./.github/actions/push-docker
        with:
          version_tag: ${{ needs.release.outputs.new_version }}
          push_latest: true # Or false, depending on your preference for release tags
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
